
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.1"

target 'berlin-transport' do
	pod 'AFNetworking'
	pod 'AFNetworkActivityLogger'
	pod 'AFOnoResponseSerializer'
	pod 'Ono'
	pod 'CHCSVParser', '~> 2.1'
end

target 'berlin-transportTests' do
	pod 'Quick'
	pod 'Nimble'
end

