source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.1"
use_frameworks!

target 'berlin-trnsprt' do
	pod 'AFNetworking'
	pod 'AFNetworkActivityLogger'
	pod 'AFOnoResponseSerializer'
	pod 'CHCSVParser'
	pod 'Ono'
	pod 'Realm'
end

target 'berlin-trnsprtTests', :exclusive => true do
	pod 'Quick'
	pod 'Nimble'
    pod 'AFNetworking'
    pod 'AFNetworkActivityLogger'
    pod 'AFOnoResponseSerializer'
    pod 'CHCSVParser'
    pod 'Ono'
    pod 'Realm/Headers'
end

